index=main sourcetype=docker_logs
| where (
    match(log, "(?i)(<script|<\/script|%3Cscript|%3C%2Fscript|javascript:|javas&#99;ript|data:text\/html|<svg|%3Csvg|<img|%3Cimg|<iframe|%3Ciframe|<object|<details|<marquee|<embed|<isindex)") OR
    match(log, "(?i)(alert\(|alert%28|alert`|confirm\(|confirm%28|confirm`|prompt\(|prompt%28|prompt`|eval\(|eval%28|atob\(|atob%28|Function\(|Function%28|\$eval|String\.fromCharCode|base64,PHNjcmlwdD)") OR
    match(log, "(?i)(\[\]\[.+\]\[.+\]|\!\!\[\]|\!\[\]|\[\]|\$\{.*\$\{.*\}\}|\+\+|--|<<|>>|\^|\|)") OR
    match(log, "(?i)(\.constructor|\.prototype|__proto__|orderBy:|\.assign|toString|getOwnPropertyDescriptor|getPrototypeOf|\$on\.constructor|\{\{|%7B%7B)") OR
    match(log, "(?i)(?:%0a|%0d|%09|%20|\\s|\\/)(?:on(?:error|load|focus|blur|mouseover|pointerover|toggle|start|click|mouseenter|dblclick))\\s*=") OR
    match(log, "\\\\u[0-9a-fA-F]{4}")
)
| stats count by _time, log, host
| rename log as "XSS_Attack_Detected"
