index=main sourcetype=docker_logs
| where (
    match(_raw, "(?i)(<script|<\/script|%3Cscript|%3C%2Fscript|javascript:|javas&#99;ript|data:text\/html|<svg|%3Csvg|<img|%3Cimg|<iframe|%3Ciframe|<object|<details|<marquee|<embed|<isindex)") OR
    match(_raw, "(?i)(alert\(|alert%28|alert`|confirm\(|confirm%28|confirm`|prompt\(|prompt%28|prompt`|eval\(|eval%28|atob\(|atob%28|Function\(|Function%28|\$eval|String\.fromCharCode|base64,PHNjcmlwdD)") OR
    match(_raw, "(?i)(\[\]\[.+\]\[.+\]|\!\!\[\]|\!\[\]|\[\]|\$\{.*\$\{.*\}\}|\+\+|--|<<|>>|\^|\|)") OR
    match(_raw, "(?i)(\.constructor|\.prototype|__proto__|orderBy:|\.assign|toString|getOwnPropertyDescriptor|getPrototypeOf|\$on\.constructor|\\{\\{|%7B%7B)") OR
    match(_raw, "(?i)(?:%0a|%0d|%09|%20|\\s|\\/)(?:on(?:error|load|focus|blur|mouseover|pointerover|toggle|start|click|mouseenter|dblclick))\\s*=") OR
    match(_raw, "\\\\u[0-9a-fA-F]{4}")
)
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "(?:GET|POST|PUT|DELETE)\s+(?<Real_Payload>.*?)\s+HTTP"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval XSS_Payload_Detallari = if(isnull(Real_Payload), _raw, Real_Payload)
| stats count as Hucum_Sayi, latest(_time) as Son_Hucum_Zamani by Hucum_Eden_IP, XSS_Payload_Detallari
| table Hucum_Eden_IP, XSS_Payload_Detallari, Hucum_Sayi, Son_Hucum_Zamani
| fieldformat Son_Hucum_Zamani=strftime(Son_Hucum_Zamani, "%Y-%m-%d %H:%M:%S")
| sort - Hucum_Sayi
