index=main sourcetype=docker_logs
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "\"log\":\"(?<Log_Detali>.*?)\",\"stream"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval Tam_Mesaj = if(isnotnull(Log_Detali), Log_Detali, _raw)
| rex field=Tam_Mesaj "(?i)(?<SQLi_Payload>(?:select|union)(?:\s|\+|%20|%2B)+.*?(?:from|select)|(?:\d+|'|%27)(?:\s|\+|%20|%2B)+(?:or|and)(?:\s|\+|%20|%2B)+.*?(?:=|>|<|like)|order(?:\s|\+|%20|%2B)+by(?:\s|\+|%20|%2B)+\d+|waitfor(?:\s|\+|%20|%2B)+delay|sleep\(|pg_sleep|xp_cmdshell|information_schema)"
| where isnotnull(SQLi_Payload)
| table _time, Hucum_Eden_IP, SQLi_Payload
