(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "Payload:\s*(?<POST_Payload>[^\"]+)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval Tam_Mesaj = if(isnotnull(POST_Payload), POST_Payload, _raw)
| rex field=Tam_Mesaj "(?i)(?<RCE_Payload>phpunit|eval-stdin|thinkphp|invokefunction|call_user_func|java\.lang\.Runtime|jndi:ldap)"
| where isnotnull(RCE_Payload)
| stats count as Hucum_Sayi, latest(_time) as Son_Zaman by Hucum_Eden_IP, RCE_Payload
| eval Risk_Skoru="Kritik (10)", Xeta="Remote Code Execution (RCE)"
| fieldformat Son_Zaman=strftime(Son_Zaman, "%Y-%m-%d %H:%M:%S")
| sort - Hucum_Sayi
