(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "\"log\":\"(?<Log_Detali>.*?)\",\"stream"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval Tam_Mesaj = if(isnotnull(Log_Detali), Log_Detali, _raw)
| rex field=Tam_Mesaj "(?i)(?<Payload>(?:\.\./|\.\.\\\\|%2e%2e%2f|%2e%2e%5c){2,}|/etc/passwd|/windows/win\.ini|boot\.ini|file://|php://filter|(?:\?|&)file=.*?(?:\.php|\.txt))"
| where isnotnull(Payload)
| stats count as Hucum_Sayi, latest(_time) as Son_Zaman by Hucum_Eden_IP, Payload
| eval Xeta_Novu="Path Traversal / LFI"
| fieldformat Son_Zaman=strftime(Son_Zaman, "%Y-%m-%d %H:%M:%S")
| sort - Hucum_Sayi
