(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "\"log\":\"(?:GET|POST)\s+(?<URL>[^\s]+)\s+HTTP.*?\"(?<Status>404|403|401)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| bin _time span=1m
| stats count as Xeta_Sayi, values(Status) as Statuslar, values(URL) as Yoxlanan_Yollar by _time, Hucum_Eden_IP
| where Xeta_Sayi > 20
| eval Risk="Yüksək", Xeta="DirBuster / Fuzzing Cəhdi"
| sort - Xeta_Sayi
