(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "\"log\":\".*?(?<UserAgent>(?i)(sqlmap|nmap|nikto|nessus|acunetix|dirb|gobuster|python-requests|masscan|zgrab))"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| where isnotnull(UserAgent)
| eval Risk_Seviyyesi = case(match(UserAgent,"(?i)(sqlmap|nikto)"), "Yüksək (8)", true(), "Orta (6)")
| stats count as Skan_Sayi, latest(_time) as Son_Zaman, values(Risk_Seviyyesi) as Risk_Skoru by Hucum_Eden_IP, UserAgent
| rename UserAgent as "Zererli_Vasite"
| fieldformat Son_Zaman=strftime(Son_Zaman, "%Y-%m-%d %H:%M:%S")
| sort - Skan_Sayi
