(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "Payload:\s*(?<POST_Payload>[^\"]+)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval Tam_Mesaj = if(isnotnull(POST_Payload), POST_Payload, _raw)
| rex field=Tam_Mesaj "(?i)(?<SQLi_Payload>(?:select|union)(?:\s|\+|%20|%2B)+.*?(?:from|select)|(?:\d+|'|%27)(?:\s|\+|%20|%2B)+(?:or|and)(?:\s|\+|%20|%2B)+.*?(?:=|>|<|like)|order(?:\s|\+|%20|%2B)+by(?:\s|\+|%20|%2B)+\d+|waitfor(?:\s|\+|%20|%2B)+delay|sleep\(|pg_sleep|xp_cmdshell|information_schema)"
| where isnotnull(SQLi_Payload)
| eval Risk_Seviyyesi=case(match(SQLi_Payload,"(?i)xp_cmdshell|union.*?select"), "Kritik (10)", match(SQLi_Payload,"(?i)sleep|waitfor"), "Yüksək (8)", true(), "Orta (6)")
| stats count as Hucum_Sayi, latest(_time) as Son_Zaman, values(Risk_Seviyyesi) as Risk_Skoru by Hucum_Eden_IP, SQLi_Payload
| fieldformat Son_Zaman=strftime(Son_Zaman, "%Y-%m-%d %H:%M:%S")
| sort - Risk_Skoru, Hucum_Sayi
