(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "Payload:\s*(?<POST_Payload>[^\"]+)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| eval Tam_Mesaj = if(isnotnull(POST_Payload), POST_Payload, _raw)
| rex field=Tam_Mesaj "(?i)(?<CMDI_Payload>(?:;|\|\||\||&&|`|\$\().*?(?:whoami|id|uname|cat\s|wget\s|curl\s|nc\s|ping\s|netstat|bash\s-i))"
| where isnotnull(CMDI_Payload)
| stats count as Hucum_Sayi, latest(_time) as Son_Zaman by Hucum_Eden_IP, CMDI_Payload
| eval Xeta_Novu="OS Command Injection", Risk_Skoru="Kritik (10)"
| fieldformat Son_Zaman=strftime(Son_Zaman, "%Y-%m-%d %H:%M:%S")
| sort - Hucum_Sayi
