(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "username=(?<Istifadeci_Adi>[^&]+)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| bin _time span=5m
| stats dc(Istifadeci_Adi) as Ferqli_Hesab_Sayi by _time, Hucum_Eden_IP
| where Ferqli_Hesab_Sayi >= 5
| eval Xeta="Credential Stuffing (Kütləvi Hesab Sındırma)"
