(index="waf" OR index="main" OR index="web_server")
| rex field=_raw "\"log\":\"(?<Real_IP>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
| rex field=_raw "\"log\":\"(?:GET|POST)\s+(?<URL>[^\s]+(?:id|user|profile)[=/-])(?<Baxilan_ID>\d+)"
| eval Hucum_Eden_IP = if(isnull(Real_IP), host, Real_IP)
| where isnotnull(Baxilan_ID)
| bin _time span=3m
| stats dc(Baxilan_ID) as Ferqli_ID_Sayi, values(Baxilan_ID) as Yoxlanan_IDler, count as Toplam_Cehd by _time, Hucum_Eden_IP
| where Ferqli_ID_Sayi >= 4
| eval Xeta="IDOR / Broken Access Control Cəhdi", Risk_Skoru="Yüksək (8)"
| sort - Ferqli_ID_Sayi
