- name: Push Rules to Splunk API
        run: |
          for file in rule/*.conf; do
            rule_name=$(basename $file .conf)
            echo "Deploying $rule_name..."
            
            # 1. Qaydanın Splunk-da olub-olmadığını yoxlayırıq
            HTTP_STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" "${{ secrets.SPLUNK_HOST }}/servicesNS/admin/search/saved/searches/$rule_name" -H "Authorization: Bearer ${{ secrets.SPLUNK_TOKEN }}")
            
            if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 201 ]; then
              echo "Qayda mövcuddur. Yenilənir (Update)..."
              curl -k -X POST "${{ secrets.SPLUNK_HOST }}/servicesNS/admin/search/saved/searches/$rule_name" \
                   -H "Authorization: Bearer ${{ secrets.SPLUNK_TOKEN }}" \
                   --data-urlencode search="$(cat $file)"
            else
              echo "Qayda yoxdur. Sıfırdan yaradılır (Create)..."
              curl -k -X POST "${{ secrets.SPLUNK_HOST }}/servicesNS/admin/search/saved/searches" \
                   -H "Authorization: Bearer ${{ secrets.SPLUNK_TOKEN }}" \
                   -d name="$rule_name" \
                   --data-urlencode search="$(cat $file)" \
                   -d "is_visible=1" \
                   -d "disabled=0" \
                   -d "sharing=app"
            fi
          done
