name: Deploy Splunk Rules

on:
  push:
    paths:
      - 'rule/*.conf'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy rules to Splunk
        run: |
          for file in rule/*.conf; do
            echo "Deploying $file..."

            curl -k -u admin:${{ secrets.SPLUNK_PASSWORD }} \
              https://139.59.161.122:8089/servicesNS/admin/search/data/lookup-table-files \
              -F "file=@$file"

          done
